In [7]:
import os
import numpy as np
import pandas as pd

In [3]:
FT_result_dir = os.path.join("..","finetune_pinnacle","tmp_model_outputs","pinnacle_seed=1")
csv_filenames = [i for i in os.listdir(FT_result_dir) if "_all_" in i]
csv_filenames

['pinnacle_all_preds_acinar cell of salivary gland.csv',
 'pinnacle_all_preds_adipocyte.csv',
 'pinnacle_all_preds_adventitial cell.csv',
 'pinnacle_all_preds_alveolar fibroblast.csv',
 'pinnacle_all_preds_artery endothelial cell.csv',
 'pinnacle_all_preds_b cell.csv',
 'pinnacle_all_preds_basal cell.csv',
 'pinnacle_all_preds_basal cell of prostate epithelium.csv',
 'pinnacle_all_preds_bladder urothelial cell.csv',
 'pinnacle_all_preds_bronchial smooth muscle cell.csv',
 'pinnacle_all_preds_bronchial vessel endothelial cell.csv',
 'pinnacle_all_preds_capillary endothelial cell.csv',
 'pinnacle_all_preds_cardiac endothelial cell.csv',
 'pinnacle_all_preds_cardiac muscle cell.csv',
 'pinnacle_all_preds_cd141-positive myeloid dendritic cell.csv',
 'pinnacle_all_preds_cd1c-positive myeloid dendritic cell.csv',
 'pinnacle_all_preds_cd24 neutrophil.csv',
 'pinnacle_all_preds_cd4-positive helper t cell.csv',
 'pinnacle_all_preds_cd4-positive, alpha-beta memory t cell.csv',
 'pinnacle_all_preds_cd8-positive, alpha-beta cytokine secreting effector t cell.csv',
 'pinnacle_all_preds_cd8-positive, alpha-beta cytotoxic t cell.csv',
 'pinnacle_all_preds_cell of skeletal muscle.csv',
 'pinnacle_all_preds_ciliary body.csv',
 'pinnacle_all_preds_ciliated cell.csv',
 'pinnacle_all_preds_ciliated epithelial cell.csv',
 'pinnacle_all_preds_classical monocyte.csv',
 'pinnacle_all_preds_club cell.csv',
 'pinnacle_all_preds_club cell of prostate epithelium.csv',
 'pinnacle_all_preds_conjunctival epithelial cell.csv',
 'pinnacle_all_preds_connective tissue cell.csv',
 'pinnacle_all_preds_corneal epithelial cell.csv',
 'pinnacle_all_preds_corneal keratocyte.csv',
 'pinnacle_all_preds_dendritic cell.csv',
 'pinnacle_all_preds_dn1 thymic pro-t cell.csv',
 'pinnacle_all_preds_dn3 thymocyte.csv',
 'pinnacle_all_preds_dn4 thymocyte.csv',
 'pinnacle_all_preds_double-positive, alpha-beta thymocyte.csv',
 'pinnacle_all_preds_duct epithelial cell.csv',
 'pinnacle_all_preds_duodenum glandular cell.csv',
 'pinnacle_all_preds_endothelial cell.csv',
 'pinnacle_all_preds_endothelial cell of artery.csv',
 'pinnacle_all_preds_endothelial cell of hepatic sinusoid.csv',
 'pinnacle_all_preds_endothelial cell of lymphatic vessel.csv',
 'pinnacle_all_preds_endothelial cell of vascular tree.csv',
 'pinnacle_all_preds_enterocyte of epithelium of large intestine.csv',
 'pinnacle_all_preds_enterocyte of epithelium of small intestine.csv',
 'pinnacle_all_preds_epithelial cell.csv',
 'pinnacle_all_preds_epithelial cell of lacrimal sac.csv',
 'pinnacle_all_preds_epithelial cell of uterus.csv',
 'pinnacle_all_preds_erythroid progenitor.csv',
 'pinnacle_all_preds_eye photoreceptor cell.csv',
 'pinnacle_all_preds_fast muscle cell.csv',
 'pinnacle_all_preds_fibroblast.csv',
 'pinnacle_all_preds_fibroblast of breast.csv',
 'pinnacle_all_preds_fibroblast of cardiac tissue.csv',
 'pinnacle_all_preds_goblet cell.csv',
 'pinnacle_all_preds_granulocyte.csv',
 'pinnacle_all_preds_gut endothelial cell.csv',
 'pinnacle_all_preds_hematopoietic stem cell.csv',
 'pinnacle_all_preds_hepatocyte.csv',
 'pinnacle_all_preds_hillock cell of prostate epithelium.csv',
 'pinnacle_all_preds_hillock-club cell of prostate epithelium.csv',
 'pinnacle_all_preds_immature enterocyte.csv',
 'pinnacle_all_preds_immature natural killer cell.csv',
 'pinnacle_all_preds_immune cell.csv',
 'pinnacle_all_preds_intermediate monocyte.csv',
 'pinnacle_all_preds_intestinal crypt stem cell.csv',
 'pinnacle_all_preds_intestinal crypt stem cell of large intestine.csv',
 'pinnacle_all_preds_intestinal crypt stem cell of small intestine.csv',
 'pinnacle_all_preds_intestinal enteroendocrine cell.csv',
 'pinnacle_all_preds_intestinal tuft cell.csv',
 'pinnacle_all_preds_intrahepatic cholangiocyte.csv',
 'pinnacle_all_preds_ionocyte.csv',
 'pinnacle_all_preds_keratinocyte.csv',
 'pinnacle_all_preds_kidney epithelial cell.csv',
 'pinnacle_all_preds_lacrimal gland functional unit cell.csv',
 'pinnacle_all_preds_langerhans cell.csv',
 'pinnacle_all_preds_large intestine goblet cell.csv',
 'pinnacle_all_preds_limbal stem cell.csv',
 'pinnacle_all_preds_limbal stromal cell.csv',
 'pinnacle_all_preds_liver dendritic cell.csv',
 'pinnacle_all_preds_luminal cell of prostate epithelium.csv',
 'pinnacle_all_preds_luminal epithelial cell of mammary gland.csv',
 'pinnacle_all_preds_lung ciliated cell.csv',
 'pinnacle_all_preds_lung microvascular endothelial cell.csv',
 'pinnacle_all_preds_lymphatic endothelial cell.csv',
 'pinnacle_all_preds_macrophage.csv',
 'pinnacle_all_preds_mature conventional dendritic cell.csv',
 'pinnacle_all_preds_mature enterocyte.csv',
 'pinnacle_all_preds_mature nk t cell.csv',
 'pinnacle_all_preds_medullary thymic epithelial cell.csv',
 'pinnacle_all_preds_melanocyte.csv',
 'pinnacle_all_preds_memory b cell.csv',
 'pinnacle_all_preds_mesenchymal stem cell.csv',
 'pinnacle_all_preds_mesothelial cell.csv',
 'pinnacle_all_preds_microglial cell.csv',
 'pinnacle_all_preds_monocyte.csv',
 'pinnacle_all_preds_mucus secreting cell.csv',
 'pinnacle_all_preds_muller cell.csv',
 'pinnacle_all_preds_muscle cell.csv',
 'pinnacle_all_preds_myeloid cell.csv',
 'pinnacle_all_preds_myeloid dendritic cell.csv',
 'pinnacle_all_preds_myeloid progenitor.csv',
 'pinnacle_all_preds_myoepithelial cell.csv',
 'pinnacle_all_preds_myofibroblast cell.csv',
 'pinnacle_all_preds_myometrial cell.csv',
 'pinnacle_all_preds_naive regulatory t cell.csv',
 'pinnacle_all_preds_naive thymus-derived cd4-positive, alpha-beta t cell.csv',
 'pinnacle_all_preds_nampt neutrophil.csv',
 'pinnacle_all_preds_nk cell.csv',
 'pinnacle_all_preds_non-classical monocyte.csv',
 'pinnacle_all_preds_ocular surface cell.csv',
 'pinnacle_all_preds_pancreatic acinar cell.csv',
 'pinnacle_all_preds_pancreatic alpha cell.csv',
 'pinnacle_all_preds_pancreatic beta cell.csv',
 'pinnacle_all_preds_pancreatic delta cell.csv',
 'pinnacle_all_preds_pancreatic ductal cell.csv',
 'pinnacle_all_preds_pancreatic pp cell.csv',
 'pinnacle_all_preds_pancreatic stellate cell.csv',
 'pinnacle_all_preds_paneth cell of epithelium of large intestine.csv',
 'pinnacle_all_preds_paneth cell of epithelium of small intestine.csv',
 'pinnacle_all_preds_pericyte cell.csv',
 'pinnacle_all_preds_plasma cell.csv',
 'pinnacle_all_preds_plasmablast.csv',
 'pinnacle_all_preds_plasmacytoid dendritic cell.csv',
 'pinnacle_all_preds_pulmonary ionocyte.csv',
 'pinnacle_all_preds_radial glial cell.csv',
 'pinnacle_all_preds_regulatory t cell.csv',
 'pinnacle_all_preds_respiratory goblet cell.csv',
 'pinnacle_all_preds_respiratory mucous cell.csv',
 'pinnacle_all_preds_retina horizontal cell.csv',
 'pinnacle_all_preds_retinal bipolar neuron.csv',
 'pinnacle_all_preds_retinal blood vessel endothelial cell.csv',
 'pinnacle_all_preds_retinal ganglion cell.csv',
 'pinnacle_all_preds_retinal pigment epithelial cell.csv',
 'pinnacle_all_preds_salivary gland cell.csv',
 'pinnacle_all_preds_schwann cell.csv',
 'pinnacle_all_preds_secretory cell.csv',
 'pinnacle_all_preds_serous cell of epithelium of bronchus.csv',
 'pinnacle_all_preds_serous cell of epithelium of trachea.csv',
 'pinnacle_all_preds_skeletal muscle satellite stem cell.csv',
 'pinnacle_all_preds_small intestine goblet cell.csv',
 'pinnacle_all_preds_smooth muscle cell.csv',
 'pinnacle_all_preds_sperm.csv',
 'pinnacle_all_preds_stromal cell.csv',
 'pinnacle_all_preds_t follicular helper cell.csv',
 'pinnacle_all_preds_tendon cell.csv',
 'pinnacle_all_preds_tongue muscle cell.csv',
 'pinnacle_all_preds_tracheal goblet cell.csv',
 'pinnacle_all_preds_transit amplifying cell of large intestine.csv',
 'pinnacle_all_preds_transit amplifying cell of small intestine.csv',
 'pinnacle_all_preds_type i nk t cell.csv',
 'pinnacle_all_preds_type i pneumocyte.csv',
 'pinnacle_all_preds_type ii pneumocyte.csv',
 'pinnacle_all_preds_vascular associated smooth muscle cell.csv',
 'pinnacle_all_preds_vein endothelial cell.csv']

In [4]:
df = pd.read_csv(os.path.join(FT_result_dir, csv_filenames[0]))
df.head()

     y     preds     name  type
0  0.0  0.514637    SHMT1  test
1  0.0  0.504812    AZGP1   val
2  0.0  0.248804  ALDH3A2  test
3  0.0  0.224450     GLRX  test
4  0.0  0.185788     KRT7   val

In [14]:
def gene_pred_extractor(csv_filename, gene_symbol="CDK6", BASE_PATH = FT_result_dir):
    df = pd.read_csv(os.path.join(BASE_PATH, csv_filename))
    cell_type_name = csv_filename.replace(".csv","").replace("pinnacle_all_preds_","")
    if gene_symbol in df["name"].values:
        score = df[df["name"] == gene_symbol]["preds"].values[0]
        return score, cell_type_name
    ## Cell does not have the gene
    else:
        return np.nan, cell_type_name

## use gene_pred_extractor with a custom gene_symbol and apply it to csv_filenames list. use map or apply to speed up things

gene_symbol = "JAK3"
results = list(map(lambda x: gene_pred_extractor(x, gene_symbol=gene_symbol), csv_filenames))
# convert the list which returns a tuple to a dataframe so that we can sort it
df_results = pd.DataFrame(results, columns=["score", "cell_type"])
## Sort by score in descending order
df_results = df_results.sort_values(by="score", ascending=False)
df_results.dropna(inplace=True)
df_results.reset_index(drop=True, inplace=True)
df_results.head()

      score                cell_type
0  0.235204          microglial cell
1  0.217462  hematopoietic stem cell
2  0.205055              granulocyte
3  0.181224  naive regulatory t cell
4  0.181009         nampt neutrophil

In [16]:
## Iterate through the filenames, load the CSV, add a column where the values will be the celltype name from the filename. Concatenate all the csvs
dfs = []
for csv_filename in csv_filenames:
    df = pd.read_csv(os.path.join(FT_result_dir, csv_filename))
    cell_type_name = csv_filename.replace(".csv","").replace("pinnacle_all_preds_","")
    df["cell_type"] = cell_type_name
    dfs.append(df)
df_all = pd.concat(dfs, ignore_index=True)

In [17]:
df_all.head()

     y     preds     name  type                      cell_type
0  0.0  0.514637    SHMT1  test  acinar cell of salivary gland
1  0.0  0.504812    AZGP1   val  acinar cell of salivary gland
2  0.0  0.248804  ALDH3A2  test  acinar cell of salivary gland
3  0.0  0.224450     GLRX  test  acinar cell of salivary gland
4  0.0  0.185788     KRT7   val  acinar cell of salivary gland

In [19]:
## Groupby the name, for each groupped dataframe, find the row with greatest preds. make a df with these rows alone
df_best = df_all.loc[df_all.groupby("name")["preds"].idxmax()]
df_best = df_best.sort_values(by="preds", ascending=False)
df_best.head(20)

         y     preds      name   type                      cell_type
8400   1.0  0.544774     FGFR3  train   conjunctival epithelial cell
24030  0.0  0.529834      TNK1   test    large intestine goblet cell
24031  1.0  0.527707  MAPKAPK5  train    large intestine goblet cell
0      0.0  0.514637     SHMT1   test  acinar cell of salivary gland
1      0.0  0.504812     AZGP1    val  acinar cell of salivary gland
47574  1.0  0.497695     PRIM2  train               type i nk t cell
41710  0.0  0.479576     ALAS1  train          retinal ganglion cell
42613  0.0  0.465789      GJA1  train                   schwann cell
16440  1.0  0.458395     POLA2   test   fibroblast of cardiac tissue
2919   1.0  0.455851      JAK2  train   bronchial smooth muscle cell
1084   0.0  0.452896     CYB5A  train            alveolar fibroblast
16441  0.0  0.451424     PTGFR  train   fibroblast of cardiac tissue
16442  1.0  0.449841     ITGAV  train   fibroblast of cardiac tissue
16443  0.0  0.448264       FTO   test   fibroblast of cardiac tissue
16444  0.0  0.446928     COX6C  train   fibroblast of cardiac tissue
16445  0.0  0.442858    TAGLN2  train   fibroblast of cardiac tissue
33872  0.0  0.440625    S100A6   test               nampt neutrophil
24032  0.0  0.439954       LTK   test    large intestine goblet cell
45640  1.0  0.431750    MAP2K1  train       t follicular helper cell
16980  1.0  0.428285    IMPDH2  train                    granulocyte